/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as DeploymentsRouteImport } from './routes/deployments'
import { Route as DefinitionsRouteImport } from './routes/definitions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as DeploymentsIndexRouteImport } from './routes/deployments.index'
import { Route as DefinitionsIndexRouteImport } from './routes/definitions.index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as InstancesIdRouteImport } from './routes/instances.$id'
import { Route as DeploymentsIdRouteImport } from './routes/deployments.$id'
import { Route as DefinitionsKeyRouteImport } from './routes/definitions.$key'
import { Route as DefinitionsKeyVersionRouteImport } from './routes/definitions.$key.$version'
import { Route as ApiMockSplatRouteImport } from './routes/api/mock/$'

const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsRoute = DeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinitionsRoute = DefinitionsRouteImport.update({
  id: '/definitions',
  path: '/definitions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const DeploymentsIndexRoute = DeploymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeploymentsRoute,
} as any)
const DefinitionsIndexRoute = DefinitionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DefinitionsRoute,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => JobsRoute,
} as any)
const InstancesIdRoute = InstancesIdRouteImport.update({
  id: '/instances/$id',
  path: '/instances/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsIdRoute = DeploymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DeploymentsRoute,
} as any)
const DefinitionsKeyRoute = DefinitionsKeyRouteImport.update({
  id: '/$key',
  path: '/$key',
  getParentRoute: () => DefinitionsRoute,
} as any)
const DefinitionsKeyVersionRoute = DefinitionsKeyVersionRouteImport.update({
  id: '/$version',
  path: '/$version',
  getParentRoute: () => DefinitionsKeyRoute,
} as any)
const ApiMockSplatRoute = ApiMockSplatRouteImport.update({
  id: '/api/mock/$',
  path: '/api/mock/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/definitions': typeof DefinitionsRouteWithChildren
  '/deployments': typeof DeploymentsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/definitions/$key': typeof DefinitionsKeyRouteWithChildren
  '/deployments/$id': typeof DeploymentsIdRoute
  '/instances/$id': typeof InstancesIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/definitions/': typeof DefinitionsIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/api/mock/$': typeof ApiMockSplatRoute
  '/definitions/$key/$version': typeof DefinitionsKeyVersionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/definitions/$key': typeof DefinitionsKeyRouteWithChildren
  '/deployments/$id': typeof DeploymentsIdRoute
  '/instances/$id': typeof InstancesIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/definitions': typeof DefinitionsIndexRoute
  '/deployments': typeof DeploymentsIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/api/mock/$': typeof ApiMockSplatRoute
  '/definitions/$key/$version': typeof DefinitionsKeyVersionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/definitions': typeof DefinitionsRouteWithChildren
  '/deployments': typeof DeploymentsRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/definitions/$key': typeof DefinitionsKeyRouteWithChildren
  '/deployments/$id': typeof DeploymentsIdRoute
  '/instances/$id': typeof InstancesIdRoute
  '/jobs/$id': typeof JobsIdRoute
  '/definitions/': typeof DefinitionsIndexRoute
  '/deployments/': typeof DeploymentsIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/api/mock/$': typeof ApiMockSplatRoute
  '/definitions/$key/$version': typeof DefinitionsKeyVersionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/definitions'
    | '/deployments'
    | '/jobs'
    | '/definitions/$key'
    | '/deployments/$id'
    | '/instances/$id'
    | '/jobs/$id'
    | '/definitions/'
    | '/deployments/'
    | '/jobs/'
    | '/api/mock/$'
    | '/definitions/$key/$version'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/definitions/$key'
    | '/deployments/$id'
    | '/instances/$id'
    | '/jobs/$id'
    | '/definitions'
    | '/deployments'
    | '/jobs'
    | '/api/mock/$'
    | '/definitions/$key/$version'
  id:
    | '__root__'
    | '/'
    | '/definitions'
    | '/deployments'
    | '/jobs'
    | '/definitions/$key'
    | '/deployments/$id'
    | '/instances/$id'
    | '/jobs/$id'
    | '/definitions/'
    | '/deployments/'
    | '/jobs/'
    | '/api/mock/$'
    | '/definitions/$key/$version'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DefinitionsRoute: typeof DefinitionsRouteWithChildren
  DeploymentsRoute: typeof DeploymentsRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  InstancesIdRoute: typeof InstancesIdRoute
  ApiMockSplatRoute: typeof ApiMockSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments': {
      id: '/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DeploymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definitions': {
      id: '/definitions'
      path: '/definitions'
      fullPath: '/definitions'
      preLoaderRoute: typeof DefinitionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/deployments/': {
      id: '/deployments/'
      path: '/'
      fullPath: '/deployments/'
      preLoaderRoute: typeof DeploymentsIndexRouteImport
      parentRoute: typeof DeploymentsRoute
    }
    '/definitions/': {
      id: '/definitions/'
      path: '/'
      fullPath: '/definitions/'
      preLoaderRoute: typeof DefinitionsIndexRouteImport
      parentRoute: typeof DefinitionsRoute
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/instances/$id': {
      id: '/instances/$id'
      path: '/instances/$id'
      fullPath: '/instances/$id'
      preLoaderRoute: typeof InstancesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$id': {
      id: '/deployments/$id'
      path: '/$id'
      fullPath: '/deployments/$id'
      preLoaderRoute: typeof DeploymentsIdRouteImport
      parentRoute: typeof DeploymentsRoute
    }
    '/definitions/$key': {
      id: '/definitions/$key'
      path: '/$key'
      fullPath: '/definitions/$key'
      preLoaderRoute: typeof DefinitionsKeyRouteImport
      parentRoute: typeof DefinitionsRoute
    }
    '/definitions/$key/$version': {
      id: '/definitions/$key/$version'
      path: '/$version'
      fullPath: '/definitions/$key/$version'
      preLoaderRoute: typeof DefinitionsKeyVersionRouteImport
      parentRoute: typeof DefinitionsKeyRoute
    }
    '/api/mock/$': {
      id: '/api/mock/$'
      path: '/api/mock/$'
      fullPath: '/api/mock/$'
      preLoaderRoute: typeof ApiMockSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DefinitionsKeyRouteChildren {
  DefinitionsKeyVersionRoute: typeof DefinitionsKeyVersionRoute
}

const DefinitionsKeyRouteChildren: DefinitionsKeyRouteChildren = {
  DefinitionsKeyVersionRoute: DefinitionsKeyVersionRoute,
}

const DefinitionsKeyRouteWithChildren = DefinitionsKeyRoute._addFileChildren(
  DefinitionsKeyRouteChildren,
)

interface DefinitionsRouteChildren {
  DefinitionsKeyRoute: typeof DefinitionsKeyRouteWithChildren
  DefinitionsIndexRoute: typeof DefinitionsIndexRoute
}

const DefinitionsRouteChildren: DefinitionsRouteChildren = {
  DefinitionsKeyRoute: DefinitionsKeyRouteWithChildren,
  DefinitionsIndexRoute: DefinitionsIndexRoute,
}

const DefinitionsRouteWithChildren = DefinitionsRoute._addFileChildren(
  DefinitionsRouteChildren,
)

interface DeploymentsRouteChildren {
  DeploymentsIdRoute: typeof DeploymentsIdRoute
  DeploymentsIndexRoute: typeof DeploymentsIndexRoute
}

const DeploymentsRouteChildren: DeploymentsRouteChildren = {
  DeploymentsIdRoute: DeploymentsIdRoute,
  DeploymentsIndexRoute: DeploymentsIndexRoute,
}

const DeploymentsRouteWithChildren = DeploymentsRoute._addFileChildren(
  DeploymentsRouteChildren,
)

interface JobsRouteChildren {
  JobsIdRoute: typeof JobsIdRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsIdRoute: JobsIdRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DefinitionsRoute: DefinitionsRouteWithChildren,
  DeploymentsRoute: DeploymentsRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  InstancesIdRoute: InstancesIdRoute,
  ApiMockSplatRoute: ApiMockSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
