-- FLOWTRACE_* audit tables. See claudedocs/backend-library-design.md §5 and
-- claudedocs/design-flyway-schema-migration.md for why this lives in a location outside Spring
-- Boot's default Flyway scan path (classpath:db/migration) rather than nested under it.

CREATE TABLE FLOWTRACE_VARIABLE_HISTORY (
    ID VARCHAR(64) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64) NOT NULL,
    EXECUTION_ID VARCHAR(64),
    VARIABLE_NAME VARCHAR(255) NOT NULL,
    VARIABLE_TYPE VARCHAR(100),
    VARIABLE_VALUE TEXT,
    CHANGE_TYPE VARCHAR(20) NOT NULL,
    CHANGED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_FLOWTRACE_VAR_HIST_PROC_INST ON FLOWTRACE_VARIABLE_HISTORY (PROCESS_INSTANCE_ID);

CREATE TABLE FLOWTRACE_JOB_ATTEMPT (
    ID VARCHAR(64) NOT NULL,
    JOB_ID VARCHAR(64) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64),
    ATTEMPT_AT TIMESTAMP NOT NULL,
    DURATION_MS BIGINT,
    OUTCOME VARCHAR(20) NOT NULL,
    EXCEPTION_MESSAGE TEXT,
    RETRIES_LEFT INTEGER,
    WORKER VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_FLOWTRACE_JOB_ATTEMPT_JOB ON FLOWTRACE_JOB_ATTEMPT (JOB_ID);

CREATE TABLE FLOWTRACE_SEQUENCE_FLOW_TAKEN (
    ID VARCHAR(64) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64) NOT NULL,
    SEQUENCE_FLOW_ID VARCHAR(255) NOT NULL,
    TAKEN_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_FLOWTRACE_SEQ_FLOW_PROC_INST ON FLOWTRACE_SEQUENCE_FLOW_TAKEN (PROCESS_INSTANCE_ID);

CREATE TABLE FLOWTRACE_DEPLOYMENT_ACTIVITY (
    ID VARCHAR(64) NOT NULL,
    DEPLOYMENT_ID VARCHAR(64) NOT NULL,
    KIND VARCHAR(20) NOT NULL,
    DETAIL VARCHAR(500),
    OCCURRED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IDX_FLOWTRACE_DEPL_ACT_DEPL ON FLOWTRACE_DEPLOYMENT_ACTIVITY (DEPLOYMENT_ID);
