-- FLOWTRACE_* audit tables. See claudedocs/design-schema-init-ddl-reset.md.
-- Executed via a plain DROP+CREATE reset (FlowTraceSchemaInitializer.resetSchema), not Flyway --
-- this is debug/trace data only, safe to lose on restart, so no migration history is kept.

CREATE TABLE IF NOT EXISTS FLOWTRACE_VARIABLE_HISTORY (
    ID VARCHAR(64) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64) NOT NULL,
    EXECUTION_ID VARCHAR(64),
    VARIABLE_NAME VARCHAR(255) NOT NULL,
    VARIABLE_TYPE VARCHAR(100),
    VARIABLE_VALUE TEXT,
    CHANGE_TYPE VARCHAR(20) NOT NULL,
    CHANGED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_FLOWTRACE_VAR_HIST_PROC_INST ON FLOWTRACE_VARIABLE_HISTORY (PROCESS_INSTANCE_ID);

CREATE TABLE IF NOT EXISTS FLOWTRACE_JOB_ATTEMPT (
    ID VARCHAR(64) NOT NULL,
    JOB_ID VARCHAR(64) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64),
    ATTEMPT_AT TIMESTAMP NOT NULL,
    DURATION_MS BIGINT,
    OUTCOME VARCHAR(20) NOT NULL,
    EXCEPTION_MESSAGE TEXT,
    RETRIES_LEFT INTEGER,
    WORKER VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_FLOWTRACE_JOB_ATTEMPT_JOB ON FLOWTRACE_JOB_ATTEMPT (JOB_ID);

CREATE TABLE IF NOT EXISTS FLOWTRACE_SEQUENCE_FLOW_TAKEN (
    ID VARCHAR(64) NOT NULL,
    PROCESS_INSTANCE_ID VARCHAR(64) NOT NULL,
    SEQUENCE_FLOW_ID VARCHAR(255) NOT NULL,
    TAKEN_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_FLOWTRACE_SEQ_FLOW_PROC_INST ON FLOWTRACE_SEQUENCE_FLOW_TAKEN (PROCESS_INSTANCE_ID);

CREATE TABLE IF NOT EXISTS FLOWTRACE_DEPLOYMENT_ACTIVITY (
    ID VARCHAR(64) NOT NULL,
    DEPLOYMENT_ID VARCHAR(64) NOT NULL,
    KIND VARCHAR(20) NOT NULL,
    DETAIL VARCHAR(500),
    OCCURRED_AT TIMESTAMP NOT NULL,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_FLOWTRACE_DEPL_ACT_DEPL ON FLOWTRACE_DEPLOYMENT_ACTIVITY (DEPLOYMENT_ID);
